### ISSUE TITLE
Add title and edit bar

### ISSUE THREAD

**Issue by hamzah-bahar** [gsg-K1-FC/Etch-a-Sketch-Hamzah#2]
### Working on : 
- [x] Title
    * Add HTML part and CSS for both style.css and media.css files to make it responsive. 
- [x] Edit Bar 
    1.  Add two input fields for rows and columns and create button
    2. Add Reset cells, Remove grid, and clear buttons
- [x] Pattern Background 
    - Resource: [Hero Patterns](https://www.heropatterns.com/)

**Comment by Jood80** [comment]
the resource thing is cool! :sparkles:
